# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MagicbellCli < Formula
  desc "MagicBell CLI."
  homepage "https://www.magicbell.com"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.3.0/magicbell-cli_darwin_amd64.tar.gz"
      sha256 "d45b64841a805e728cf101c8b825c6d3d531014277080f90451eaa4d755637f7"

      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.3.0/magicbell-cli_darwin_arm64.tar.gz"
      sha256 "3ae092ad45ffdc880c0239b1693a65ee4bf8524f71fe396dd5cafd1772196399"

      def install
        bin.install "magicbell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.3.0/magicbell-cli_linux_amd64.tar.gz"
      sha256 "2f7f6efccc0ba6a64e44fc33079ae652e2e261aaef17d83e55d318615eee0566"
      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.3.0/magicbell-cli_linux_arm64.tar.gz"
      sha256 "d46ca572e14ecc2fdc2a08c6f5b77145e5800643bfe9b07c94c2bd65913faf72"
      def install
        bin.install "magicbell"
      end
    end
  end
end
