# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Magicbell < Formula
  desc "MagicBell CLI."
  homepage "https://www.magicbell.com"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Darwin_x86_64.tar.gz"
      sha256 "44c59da179140479d5ab2e6a83d63baaac112390b5e5c2225ec5348f74657530"

      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Darwin_arm64.tar.gz"
      sha256 "397199bc30fc35f21db55e3d14a682d6fc18caaec57d1e1d4243301a623db5bb"

      def install
        bin.install "magicbell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Linux_x86_64.tar.gz"
      sha256 "19ef9ab0e3d0374408d7f30b68dfe53beb53057a7db8fc1083af55b7cf73598f"
      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Linux_arm64.tar.gz"
      sha256 "fb472965a8b36afa68e3cf4795c2b18937e69a8cbe1bd31cc5f0456d3eb159b7"
      def install
        bin.install "magicbell"
      end
    end
  end
end
