# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MagicbellCli < Formula
  desc "MagicBell CLI."
  homepage "https://www.magicbell.com"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.3/magicbell-cli_darwin_amd64.tar.gz"
      sha256 "fa00ff74b15804550f1b5871b4aadfac433b37e076f3aecc67e15f15473701b7"

      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.3/magicbell-cli_darwin_arm64.tar.gz"
      sha256 "61e2a51b4a9b1f36720c547d13b2466d263ae9347d7d8420beb5a9cd604ddeea"

      def install
        bin.install "magicbell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.3/magicbell-cli_linux_amd64.tar.gz"
      sha256 "78108ab19fa8a467a94a96df060e01546747ffb1d597c6ff023709603ff6e8df"
      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.3/magicbell-cli_linux_arm64.tar.gz"
      sha256 "cdc1494cc97fc43dbd110bcac273c49470d10280d90b1be8864ad16468bb7b4c"
      def install
        bin.install "magicbell"
      end
    end
  end
end
