# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Magicbell < Formula
  desc "MagicBell CLI."
  homepage "https://www.magicbell.com"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Darwin_x86_64.tar.gz"
      sha256 "93ea80ec8e7bea03ef6a83fbcac3d847d10a07e7dad094d2babda4a64c9deb8b"

      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Darwin_arm64.tar.gz"
      sha256 "43a7a836d42dade0286cd72ab37e8bbb55052969351a230386ee72acc2d91ed9"

      def install
        bin.install "magicbell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Linux_x86_64.tar.gz"
      sha256 "5fbe00c0287d7264fe6abe5cbbcf5edb32f5009e6be621def366c0cd6a5d95e6"
      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v0.0.1/magicbell-cli_Linux_arm64.tar.gz"
      sha256 "7e912da262f3c73e1d0b932d82e8b5fbb86cc86b2e5960c544300762cc979b36"
      def install
        bin.install "magicbell"
      end
    end
  end
end
