# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MagicbellCli < Formula
  desc "MagicBell CLI."
  homepage "https://www.magicbell.com"
  version "1.2.0-beta.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.2.0-beta.9/magicbell-cli_darwin_amd64.tar.gz"
      sha256 "25cac3cfd1215d32ddc8d9078321e49e132ad3d18e94896096176be92e51b652"

      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.2.0-beta.9/magicbell-cli_darwin_arm64.tar.gz"
      sha256 "e2edcf3e966482f7c6693ef2dfb04c7327493e0e6a4f760478db13877e4fa13f"

      def install
        bin.install "magicbell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.2.0-beta.9/magicbell-cli_linux_amd64.tar.gz"
      sha256 "aba5549c03e3bc858528daf4c801d612281d1e5c57e61731481015926ad57b40"
      def install
        bin.install "magicbell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicbell/homebrew-tap/releases/download/v1.2.0-beta.9/magicbell-cli_linux_arm64.tar.gz"
      sha256 "6d96540d268a99f39c59abd46663a85e9d0a9dbd29255c639e8d1e504cfff87b"
      def install
        bin.install "magicbell"
      end
    end
  end
end
