
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install formula
        run: brew install --include-test --formula Formula/magicbell-cli.rb
      - name: Test
        run: brew test magicbell-cli

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'MagicBella' }}
    steps:
      - name : merge
        uses : nbrugger-tgm/merge-pr-action@v0.2.3
        with :
          pull_request: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          method: squash